### ISSUE TITLE
Comments field (for edits)

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#19]
Would it be possible to add another field to the end of the form for comments, which are displayed in the pull request but not actually added to the list record?

This could function as a simple way of enabling edits; someone who has previously submitted an entry can just submit a new entry and let us know that we should delete their previous record.

Thoughts?

**Comment by unode** [comment]
Not sure this is possible. I don't see any way in the docs to have a comment go into the PR text instead of the JSON data file.

**Comment by WhoIsJack** [comment]
I see; fair enough! In that case we'll just stick with the "raise issue or send email" option for edits.
