### ISSUE TITLE
Unexpected Effects of Special Char Restrictions

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#197]
I think they should only affect Name and Affiliation, as they're the fields that end up in file names. See also #193.

**Comment by WhoIsJack** [comment]
Reverted your change for now.

**Comment by unode** [comment]
The issue seems to be that spaces were not allowed in the pattern.
But like spaces there may be other characters that should perhaps be allowed.
I'll try to invert the pattern and instead deny only problematic characters.

**Comment by unode** [comment]
Pushed `[^\/]{1,100}` now in c5df2b43cde480cabc1b3f81ff6821a7f3162174
Tested locally and it passed. I believe before it was also forcefully expecting 100 characters.

**Comment by WhoIsJack** [comment]
Thanks for the fix, Renato! Inverting the pattern seems like a very good solution. 👍 

St*ff happens; no worries. We didn't get any other emails, so people may have just tried again a bit later, when I had already reverted it. 😌

**Comment by unode** [comment]
Thanks for the quick action on your part :rocket:
