### ISSUE TITLE
Links to Learning Materials

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#25]
I was wondering if we want to link to something related to learning materials or courses in the main page's `Other Resources` section. I think you were suggesting something along these lines, @Lisanna?

**Comment by Lisanna** [comment]
I was suggesting that the project proponents group is well qualified to deliver on-demand courses if needed. Maybe we could link The Carpentries / CodeRefinery materials and add that if enough people are interested we can organise related courses?

**Comment by WhoIsJack** [comment]
Ok, sounds good. We can certainly include those links.

As for the question of organizing courses, I reckon we could link to a survey that aims to get an idea of how much interest there is (and in what). Would you be interested in putting this together?

Organizationally, I think we should keep potential courses cleanly separated from the expert list, as the two are very different offerings.

**Comment by WhoIsJack** [comment]
Links added. Anyone who would like to add other links or a survey, please feel free to do so.

**Comment by WhoIsJack** [comment]
Lisanna has added a thing asking people to email us if they are interested in courses, so I'm closing here for now.

**Comment by WhoIsJack** [comment]
I've changed the passage asking people to send us an email if they're interested in training workshops; it now links to a Google form instead. I think this will be easier to handle, as it's separate from any other emails (like bug reports or CoC stuff), doesn't implicitly require us to write an answer for each request (emails kind of do), and summarizes the responses automatically.
