### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#4]
Would be nice if the list was searchable, e.g. using a simple free-text search similar to that available in the [EMBO list](https://www.embo.org/solidarity-with-ukraine/).

One possibly quite easy solution could be [Simple Jekyll Search](https://github.com/christian-fei/Simple-Jekyll-Search); see tutorial [here](https://blog.webjeda.com/instant-jekyll-search/).

I can try and figure this out later this week or over the weekend, but if someone else (maybe with more Jekyll know-how) would like to give it a go before then, that would be even better! ;)

**Comment by unode** [comment]
Another possibility that appeared while trying to fix #7 was [Shuffle.js](https://vestride.github.io/Shuffle/)

**Comment by unode** [comment]
I'll have a go at this over the weekend.

**Comment by WhoIsJack** [comment]
Absolutely excellent work, @unode! Looks and works great! 🎉

**Comment by unode** [comment]
There's a little of a hack going on. We should keep an eye on performance once the list starts growing to a few hundred records. The page shuffles records on load so this will also stress lower end computers/mobile devices.

Speaking of mobile, I didn't test there yet. Feedback is welcome.

One caveat is there is currently no pagination. This would be difficult regardless given we don't have a dynamic server behind.

**Comment by WhoIsJack** [comment]
Ok, we'll keep an eye on performance, especially if the number of people signed up grows really big.

Mobile seems to work and looks ok for me! 👍
