### ISSUE TITLE
Code of Conduct Deployment Error

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#40]
Since merging the Code of Conduct (PR #20), deployment fails with `Error: Request failed with status code 400`.

I've tried fixing the email links in the CoC and changing the way the title of the file is handled. I've also googled and looked file naming and cases, but didn't figure out what the problem is.

If anyone has a good idea about what's happening here, please respond or go ahead and fix it. Otherwise, I'll have to start systematically dissecting the CoC file and file name to see what works and what doesn't.

**Comment by WhoIsJack** [comment]
Huh... it seems to have fixed itself after @Lisanna's latest commit, though I can't discern the reason. 🤨

**Comment by Lisanna** [comment]
I... have no idea? We have the same roles!
I did my last edits (and committed) directly through the GitHub interface.

**Comment by WhoIsJack** [comment]
It happened again, but this time I'm pretty sure it's not due to something I did wrong.

Looks like there are now SO posts like [this one](https://stackoverflow.com/questions/71511767/github-pages-fails-to-deploy) popping up; apparently GitHub is experiencing intermittent problems with Pages and possibly other services. So this is not on us. 😌
