### ISSUE TITLE
Member subpage

### ISSUE THREAD

**Issue by unode** [Research-Support-Network/research-support-network.github.io#45]
Implement a subpage for every member.

Advantages:
1. Can hold a comment section using [utterances](https://utteranc.es/).
2. Will workaround the truncation issue with cards in the member list page (present since ed378b13d60b63e534ad5a24f31134df0daad34b - to avoid card text overflow).
3. Hold additional (potentially verbose) information or fields that don't fit in the card.

**Comment by unode** [comment]
1. Took the liberty to [create a RSN space in matrix.org](https://matrix.to/#/#research-support-network:matrix.org). If you all agree we can add this to the README and the page.
2. We may want to do this validation with some kind of action on GitHub. I don't see how to do it through staticman.
3. I agree on this. Lets park it here.

**Comment by WhoIsJack** [comment]
1. Didn't know about matrix.org; looks neat, will have to try it out!
2. Interesting; I'm learning a lot of new stuff about GitHub! I was actually just thinking of [maxlength](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength); is there a reason this should not be used? I suppose there's probably ways of circumventing it, so having the backend validation is good, but it would be nice if users were stopped directly on the frontend if they exceed the number of characters allowed. Setting `maxlength` should do this.

**Comment by WhoIsJack** [comment]
I've added the `maxlength` and it seems to work.

(Reopened issue in case this needs further discussion; feel free to close.)

**Comment by unode** [comment]
`maxlength` sounds a lot more sane to me. Thanks for adding this. I also learned something today.
Leaving the backend validation in place in case we need more elaborate logic in the future.

**Comment by unode** [comment]
> Didn't know about matrix.org; looks neat, will have to try it out!

Think of it as IRC 2.0 (or maybe 3.0) :)
