### ISSUE TITLE
Add Language Field

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#5]
I think we should add another field in the list to declare languages spoken. Some people may be more comfortable speaking to a supporter in a language other than English.

That said, the language for the free-text `Expertise` field should be English only to facilitate moderation. I will add a note on this to the form when I work through issue #3.

**Comment by unode** [comment]
This requires an edit to two files [the form](https://github.com/Research-Support-Network/research-support-network.github.io/blob/main/add.md) and [the submission engine](https://github.com/Research-Support-Network/research-support-network.github.io/blob/main/staticman.yml) (see `allowedFields` and `requiredFields` in the yaml file).
