### ISSUE TITLE
Launch Testing 💥 

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#51]
Hi everyone,

As per my email, please each submit a few (3-5) forms with different kinds of entries on Wednesday (23.03.22) afternoon, especially around 3pm GMT if you have time (doesn't need to be *exactly* 3pm, though).

This is to stress test the site / form / staticman engine. Feel free to try entering some things that you're not supposed to (empty fields, too much text, etc.).

Please report any issues you encounter in this thread! Thanks!

**Comment by WhoIsJack** [comment]
@Lisanna - Renato should be able to see the logs and maybe find out what caused the error. At least it seems that the engine hasn't crashed as in issue #13, unless @unode has restarted it between your tests and Elisabeth's.

@ElisabethKugler - Great; thanks!

**Comment by WhoIsJack** [comment]
I've just merged and rejected a variety of the test submissions and tested whether the engine still works after that (there was some worry that this could cause problems, as per issue #13). Worked fine this time around, though.

**Comment by unode** [comment]
aaand managed to break it by repeatedly submitting the same content.

**Comment by unode** [comment]
```
2022-03-23T14:41:01.337503+00:00 heroku[router]: at=info method=POST path="/v1/webhook" host=research-support-network.herokuapp.com request_id=ac4c16b3-dc9a-471e-b1ad-f325424bda2f fwd="140.82.115.96" dyno=web.1 connect=0ms service=7ms status=200 bytes=223 protocol=https
2022-03-23T14:41:01.543549+00:00 heroku[router]: at=info method=POST path="/v1/webhook" host=research-support-network.herokuapp.com request_id=151a95a2-73f1-477b-96b5-e655794eb714 fwd="140.82.115.108" dyno=web.1 connect=0ms service=8ms status=200 bytes=223 protocol=https
2022-03-23T14:41:02.839536+00:00 heroku[web.1]: Process exited with status 1
2022-03-23T14:41:02.685298+00:00 app[web.1]: /app/node_modules/@octokit/request/dist-node/index.js:66
2022-03-23T14:41:02.685312+00:00 app[web.1]: const error = new requestError.RequestError(message, status, {
2022-03-23T14:41:02.685313+00:00 app[web.1]: ^
2022-03-23T14:41:02.685314+00:00 app[web.1]: 
2022-03-23T14:41:02.685314+00:00 app[web.1]: RequestError [HttpError]
2022-03-23T14:41:02.685315+00:00 app[web.1]: at /app/node_modules/@octokit/request/dist-node/index.js:66:23
2022-03-23T14:41:02.685315+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-23T14:41:02.685316+00:00 app[web.1]: at async GitHub._authenticate (/app/lib/GitHub.js:60:20)
2022-03-23T14:41:02.685317+00:00 app[web.1]: at async /app/lib/GitHub.js:31:21
2022-03-23T14:41:02.685317+00:00 app[web.1]: at async Function.module.exports (/app/controllers/handlePR.js:16:18) {
2022-03-23T14:41:02.685317+00:00 app[web.1]: status: 500,
2022-03-23T14:41:02.685318+00:00 app[web.1]: headers: {
2022-03-23T14:41:02.685318+00:00 app[web.1]: connection: 'close',
2022-03-23T14:41:02.685318+00:00 app[web.1]: date: 'Wed, 23 Mar 2022 14:41:02 GMT',
2022-03-23T14:41:02.685319+00:00 app[web.1]: server: 'GitHub.com',
2022-03-23T14:41:02.685319+00:00 app[web.1]: 'transfer-encoding': 'chunked',
2022-03-23T14:41:02.685319+00:00 app[web.1]: vary: 'Accept-Encoding, Accept, X-Requested-With',
2022-03-23T14:41:02.685320+00:00 app[web.1]: 'x-github-request-id': '8A88:EFC3:16C4B4:17244A:623B317C'
2022-03-23T14:41:02.685320+00:00 app[web.1]: },
2022-03-23T14:41:02.685320+00:00 app[web.1]: request: {
2022-03-23T14:41:02.685321+00:00 app[web.1]: method: 'GET',
2022-03-23T14:41:02.685322+00:00 app[web.1]: url: 'https://api.github.com/repos/Research-Support-Network/research-support-network.github.io/installation',
2022-03-23T14:41:02.685322+00:00 app[web.1]: headers: {
2022-03-23T14:41:02.685323+00:00 app[web.1]: accept: 'application/vnd.github.machine-man-preview+json',
2022-03-23T14:41:02.685323+00:00 app[web.1]: 'user-agent': 'octokit-request.js/5.3.1 Node.js/17.6.0 (Linux 4.4; x64)',
2022-03-23T14:41:02.685323+00:00 app[web.1]: authorization: 'Bearer [REDACTED]'
2022-03-23T14:41:02.685323+00:00 app[web.1]: }
2022-03-23T14:41:02.685324+00:00 app[web.1]: }
2022-03-23T14:41:02.685324+00:00 app[web.1]: }
2022-03-23T14:41:02.685329+00:00 app[web.1]: 
2022-03-23T14:41:02.685330+00:00 app[web.1]: Node.js v17.6.0
2022-03-23T14:41:02.931675+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by ElisabethKugler** [comment]
Do you still want us to test with you simultaneously? Coffee at hand and keyboard warmed up.

**Comment by unode** [comment]
Using:

```
for i in $(seq 1 10) ; do curl 'https://research-support-network.herokuapp.com/v3/entry/github/Research-Support-Network/research-support-network.github.io/main/member-submission' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: https://research-support-network.github.io' -H 'Connection: keep-alive' -H 'Referer: https://research-support-network.github.io/' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: cross-site' -H 'Sec-Fetch-User: ?1' -H 'DNT: 1' -H 'Sec-GPC: 1' --data-raw "options%5Bredirect%5D=https%3A%2F%2Fresearch-support-network.github.io%2Fsubmitted.html&options%5Bslug%5D=&fields%5Bname%5D=Renato+Test+Try+C+$i&fields%5Baffiliation%5D=Here&fields%5Bcountry%5D=None&fields%5Bemail%5D=try+%40+this+dot+com&fields%5Bwebsite%5D=null&fields%5Blanguages%5D=Esperanto&fields%5Bexpertise%5D=Some" ; sleep 1 ; done
```
seems to reliably crash the server after 2 or 3 requests.

This looks a little too fragile :sob:

**Comment by unode** [comment]
Feel free to test manually now. I'll keep an eye.

**Comment by WhoIsJack** [comment]
Ok, thanks Renato! 🤞

**Comment by WhoIsJack** [comment]
Thanks a lot, Renato!

It is unsettling, but overall I'd say stability isn't too bad, so I'm wondering if we can launch anyway and hope for the best? (Sounding like a C-level person here... 😅 )

We can put some mitigation in place:
- [x] Option to quickly switch to Google form if things fail repeatedly
- [ ] Add note above submit button asking people to come back in a few hours if they receive an application error
- [ ] Keeping a close eye on the engine during the first few days to restart if needed
    - Any way for us to help with that so it isn't all on Renato?
    - Any chance for regular automated restarts, e.g. every hour? I've asked about cron before and @unode said it's not possible, but maybe there is some other way? How involved is the manual restart?

**Comment by unode** [comment]
Adding a note sounds good. The timeout is 1 hour so, "try again in 2 hours seems adequate".
Looking into ways to reduce this timeout but no luck so far.

Regarding logs, and restarting the engine, I'll see if I can hack something together.

I noticed that the system seems to heal itself at some points in time. Not sure what triggers it. I'm trying to cause another crash. From the last log record it looks like visiting http://research-support-network.herokuapp.com when the engine is crashed may bring it back to life but I haven't been able to test this yet.

**Comment by unode** [comment]
Ok, no it doesn't restart by itself. Working on a workaround.

**Comment by nrstillman** [comment]
Just gave a couple of simple tests (unicode, blank spaces etc.) and no problems here. 

I wonder whether we need country as info rather than timezone as a dropdown option? Not sure if I get the rational for including that (where country is already implied by affiliation)

**Comment by WhoIsJack** [comment]
Thanks for testing, @nrstillman!

I was actually wondering about `Country` as well, but mainly due to its ambiguity, as it could be interpreted as location or nationality. You're right that what really matters for remote support is time zone, so I really like the idea of a time zone dropdown menu.

Regarding implementation:
- What makes you think that staticman would do poorly with a `select` element within the form (instead of the currently used `input`)?
- That aside, I found various implementations of time zone `select` widgets, but they all use a pre-made list of time zones rather than pulling from some official source, which seems a bit odd... but I guess it would be good enough for now.

**Comment by unode** [comment]
> (...) dynamic version in perl (...)

I suspect the idea in our case is to run it once to generate the HTML template.

> What makes you think that staticman would do poorly with a `select` element within the form (instead of the currently used `input`)?

Should be handled fine. We just need to make sure that the identifier for each option carries meaning as that's likely what will end up in the pull request.

> I was actually wondering about `Country`

We want "Country where you work" right? Also, I don't think `Nationality` is [relevant here](https://www.ted.com/talks/taiye_selasi_don_t_ask_where_i_m_from_ask_where_i_m_a_local?language=en).

**Comment by WhoIsJack** [comment]
If the time zone option works, I think that would be perfect! 💎 

Otherwise, I agree that "Country where you work" should be the intended use, so we could just clarify this in the form (or remove it, as it is somewhat redundant with `Affiliation`, as Namid pointed out).

**Comment by unode** [comment]
There are some cases where `Affiliation` alone can be ambiguous. I don't have the example at hand but I recall finding institutions with the exact same name in entirely different countries.

The email would likely disambiguate but I'd vouch for explicit over implicit.

**Comment by WhoIsJack** [comment]
> There's now a workaround in place. 

This is great, Renato! Very simple and should keep us afloat if the occasional error occurs.

I've also added a note above the submit button telling people to retry a few hours later if they run into an Application Error. 


> The email would likely disambiguate but I'd vouch for explicit over implicit.

Agreed. So should we go for a time zone widget? I could add the HTML one, which might be good enough. If we want to go with running the Perl script during deployment, I'm afraid I'm going to have to rely on Renato again. 😅 

In the meantime, I've added a note to the `Country` field providing clarification, so if we decide against the time zone widget or if it doesn't work we can just go with this.

---

Finally, I've noticed (while updating the emergency branch) that we had a ton of staticman branches left 'dangling'. I'm guessing that after a crash+restart, branches are no longer auto-deleted even if the PR has been merged or closed. Not really a problem, though; it's easy to occasionally go and clean up stale branches.

**Comment by unode** [comment]
> running the Perl script during deployment

We won't see timezones changing that often so I would say run once locally, commit and keep the perl script in the repo for a future update. We don't need to integrate it with the CI. A one-off should do fine.

> clean up stale branches

I noticed this too yesterday. Crashed likely lead to staticman losing its state so the rest is somewhat expected.
I assume this happens if we close a PR when staticman is down or crashed.

We could potentially even use this as breadcrumbs to know when things took a wrong turn.

**Comment by WhoIsJack** [comment]
I've swapped `Country` for `Timezone` now; hopefully I've adapted everything correctly. A few tests seem to indicate that I did.

@unode: could you please double-check that I didn't bork anything up (see mainly #167 and subsequent couple of commits) and maybe run a couple more tests?

Once this is done, I think we're good to go.

**Comment by unode** [comment]
Looks good to me.

Got an error on the first attempt. Engine was down and seems like it didn't wake up quick enough.
Hit back, submitted again and it all worked.

I think we are good to go.

**Comment by nrstillman** [comment]
Nice work — I attempted googling an implementation of this but came up short when I looked before. 

Just tried to submit and all went smoothly on my end. 

Great work all!

**Comment by ElisabethKugler** [comment]
That's great. Thanks, everyone! Are we good to start sharing with others?

**Comment by WhoIsJack** [comment]
Great, thanks everyone! 🎉 

I'll get the last bits of launch prep done asap and will let you know when it's time to go live!

**Comment by unode** [comment]
Do we want to prepare some Tweet texts to go along with the release? Or is that what you mean by prep :)

**Comment by WhoIsJack** [comment]
Sure, if anyone would like to draft a Tweet that people can use as a basis for theirs, that would be great! People can also go free-form, though - whatever everyone prefers.

Last prep still to do:
- [x] Google form for training requests
- [ ] Remove existing list entries
- [ ] Remove "under construction" tag from index
- [ ] Wait for GitHub to get the deployment running

**Comment by WhoIsJack** [comment]
@unode 

Hm... the deployment doesn't seem to work. It keeps repeating `Current status: updating_pages` (I think this shouldn't happen if things are working) and after several minutes either fails with `Error: Request failed with status code 400` (which we had before and was on GitHub's side) or with `Error: Request failed with status code 502`, which I've not seen before.

Any thoughts?

**Comment by unode** [comment]
I see you got to it before me and the issue seems to be fixed now.

**Comment by unode** [comment]
Updated the emergency branch to the latest.

**Comment by WhoIsJack** [comment]
Alright, it all looks good to go. Will write an email to everyone now. Closing here,
