### ISSUE TITLE
Shuffling the list

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#7]
It would be good if the list could be randomly shuffled each time it is displayed to avoid a situation where the top `n` volunteers receive 90% of all emails.

I'm guessing that this could be done by changing this for-loop

```{% for member_name in site.data.members %} {% assign member = member_name[1] %}```

to iterate over a shuffled version of `site.data.members`?

**Comment by unode** [comment]
I'm afraid we will have to do this randomization with JavaScript if we want the page to display a different order to different visitors.
Anything implemented in Jekyll (Liquid) is only going to execute a single time when the site is generated, that is, when new members or changes are made to the repository.

**Comment by unode** [comment]
This may also be easier to do together with #4

**Comment by WhoIsJack** [comment]
How feasible is this? I'm totally out of touch with this stuff...

**Comment by unode** [comment]
Should be quite feasible as long as we keep all members in a single page (without pagination).

**Comment by unode** [comment]
https://css-tricks.com/snippets/jquery/shuffle-children/ looks like a simple way to write the code.

**Comment by unode** [comment]
Confirmed that it is working. Refresh the page multiple times to see the effect.
I assume it will be more noticeable once more cards are visible.
