### ISSUE TITLE
Contact Email

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#8]
We need a contact email. I'd be happy to give mine, but I think it would be better to create one that can be accessed by any of the repo's current and future maintainers.

I suppose we could just make a gmail account for this, unless anyone can think of any potential issues this might cause and/or of any better options?

**Comment by unode** [comment]
Perhaps [a confidential mailing list in Google](https://smallbusiness.chron.com/create-confidential-mailing-list-google-52291.html)?

**Comment by WhoIsJack** [comment]
Good idea. I will try this!

**Comment by WhoIsJack** [comment]
This seems to no longer be an option. The new version of Google doesn't have groups, but rather has "lists".

I've decided to just make a new Gmail account and share the details with y'all.

The email for list users to write to is expertvolunteerlist@gmail.com. I will include this in the relevant places on the site.
